#!/usr/bin/env bash
# configure ufw so that it blocks all incoming traffic except port 22 80 443
sudo ufw default deny incoming
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
sudo ufw enable
